### ISSUE TITLE
Exec in existing container. Maybe dockerComposeExec? 

### ISSUE THREAD

**Issue by libasoles** [droath/robo-docker-compose#1]
Nice initiative. 
Do you have any idea on how to run a task on an existing docker container?
Like:
`$this->taskExec('docker exec -ti php-container bash -c "cd /src && vendor/bin/phpunit"')->run();
`
That code fails within Robo but works in console. 

And I also tried using the Docker tasks, but they require you to run an instance first, and I don't want to do that. I want to use an existing container. 

```
$container = $this->taskDockerRun('php')  <- I don't want to do this
            ->detached()
            ->run();

        $this->taskDockerExec($container)
            ->interactive()
            ->dir('/src')
            ->exec('./vendor/bin/phpunit')
            ->run();
```

Maybe you are planning to create a dockerComposeExec method?

EDIT: oh, I'm talking about compose because I run my containers throw a docker-compose.yml file. And the official Robo/DOcker tasks are intended to work with individual containers.

**Comment by droath** [comment]
@libasoles 

Sorry its been awhile to get a solution in place. I now have support for `docker-compose exec`, I've attached an example of what a basic command would look like.

This will execute `composer install` within the `php` container.

```php
$container = 'php';
$command = 'composer -d /working/dir install';
            
$result = $this->taskDockerComposeExecute()
  ->setContainer($container)
  ->exec($command)
  ->run();
```
